name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install github-contribution-grid-snake

      - name: Gerar cobrinha
        run: npx github-contribution-grid-snake --user StealthByt --color FF00FF

      - name: Commit e push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Atualizar cobrinha do GitHub"
          git push
